#!/bin/php
<?php

use Library\Command\Console;
use Library\Command\Flag;

require_once 'utils.php';

$plugin = Console::add('🔌', 'plugin', 'Manage you plugins', function () {});
$plugin->flag_add(new Flag('i', 'install', 'install new plugin from github', 0, function () {}));
$plugin->flag_add(new Flag('d', 'delete', 'delete a plugin', 0, function () {}));

Console::init($argv);
